services:
  mongo:
    image: mongo:4.2.5
    ports:
      - '27017:27017'
  web:
    build: .
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - '8080:8080'
    #restart: always
    #port:
      #- "27017:27017"